-- 시퀀스 생성
DROP SEQUENCE EMP_SEQ;

CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000
NOCYCLE
CACHE 2;
-- USER_TABS, USER_CONSTRAINTS, USER_CONTS_COLUMNS, USER_VIEWS, USER_INDEXES, USER_SEQUENCES
SELECT * FROM user_sequences;

-- EMPLOYEES 구조만 복사 EMP01
DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE 1 = 0;

SELECT * FROM EMP01;
DESC EMP01;
-- EMP_SEQ.NEXTVAL 입력하기
INSERT INTO EMP01 VALUES (EMP_SEQ.NEXTVAL, 'KDJ', SYSDATE);

-- EMP_SEQ.CURVAL 입력하기
SELECT EMP_SEQ.CURRVAL FROM DUAL;

-- SEQUENCE DEPT_SEQ 생성, 시작값 10, 증가치 10, 결과치 30
CREATE SEQUENCE DEPT_SEQ
START WITH 10
INCREMENT BY 10
MAXVALUE 30;

SELECT * FROM user_sequences;

-- DEPT02 테이블을 구조 복사
DROP TABLE DEPT02;

CREATE TABLE DEPT02
AS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM DEPARTMENTS WHERE 1 = 0;

INSERT INTO DEPT02 VALUES (DEPT_SEQ.NEXTVAL, '인사과', 1);
INSERT INTO DEPT02 VALUES (DEPT_SEQ.NEXTVAL, '총무과', 2);
INSERT INTO DEPT02 VALUES (DEPT_SEQ.NEXTVAL, '서무과', 3);
INSERT INTO DEPT02 VALUES (DEPT_SEQ.NEXTVAL, '교육과', 4);

SELECT * FROM DEPT02;

-- SEQUENCE 수정
ALTER SEQUENCE DEPT_SEQ
MAXVALUE 100;

SELECT * FROM user_sequences WHERE SEQUENCE_NAME = 'DEPT_SEQ';

-- SEQUENCE 삭제
DROP SEQUENCE DEPT_SEQ;

-- 데이터 딕셔너리에서 인덱스 확인
SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'EMPLOYEES';
SELECT * FROM user_ind_columns WHERE TABLE_NAME = 'EMPLOYEES';

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;

DROP TABLE EMP10;

CREATE TABLE EMP10
AS
SELECT * FROM EMPLOYEES WHERE 1 = 1;

SELECT * FROM EMP10 WHERE EMPLOYEE_ID = 100;

-- 인덱스 생성
SELECT * FROM user_ind_columns WHERE TABLE_NAME = 'EMP10';

CREATE UNIQUE INDEX EMP10_EMPLOYEE_IX
ON EMP10(EMPLOYEE_ID);

-- 인덱스 삭제하기
DROP INDEX  EMP10_EMPLOYEE_IX;






















