-- MVC 모델방식 적용
SELECT * FROM STUDENT;
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    NO NUMBER(4), -- PK
    NAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4) NOT NULL,
    ENG NUMBER(4)NOT NULL,
    MAT NUMBER(4)NOT NULL,
    TOTAL NUMBER(4),
    AVE NUMBER(5,1),
    RANK NUMBER(4)
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_NO_PK PRIMARY KEY(NO);

DROP SEQUENCE STUDENT_STUNUM_SEQ;
CREATE SEQUENCE STUDENT_NO_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO STUDENT (NO,NAME,KOR,ENG,MAT) VALUES(STUDENT_NO_SEQ.NEXTVAL, '홍길동', '90', '70', '70');
INSERT INTO STUDENT (NO,NAME,KOR,ENG,MAT) VALUES(STUDENT_NO_SEQ.NEXTVAL, '김길동', '80', '25', '66');
INSERT INTO STUDENT (NO,NAME,KOR,ENG,MAT) VALUES(STUDENT_NO_SEQ.NEXTVAL, '이길동', '100', '75', '89');
COMMIT;


SELECT * FROM STUDENT;

-- 성적을 입력하면 총점과 평균이 자동 계산되어 입력되는 트리거
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER
BEFORE INSERT ON STUDENT
FOR EACH ROW
BEGIN
    :NEW.TOTAL := :NEW.KOR + :NEW.ENG + :NEW.MAT;
    :NEW.AVE := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MAT) / 3, 1);
END;
/

-- 성적을 수정하면 총점과 평균이 같이 변하는 트리거
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER2
BEFORE UPDATE ON STUDENT
FOR EACH ROW
BEGIN
    :NEW.TOTAL := :NEW.KOR + :NEW.ENG + :NEW.MAT;
    :NEW.AVE := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MAT) / 3, 1);
END;
/

-- 등수를 처리하는 저장 프로시저 생성
CREATE OR REPLACE PROCEDURE STUDENT_RANK_PROC
IS 
    VSTUDENT_RT STUDENT%ROWTYPE; 
    CURSOR C1 IS
    SELECT NO, NAME, RANK() 
    OVER(ORDER BY TOTAL DESC) RANK FROM STUDENT ORDER BY TOTAL DESC; 
BEGIN
    FOR  VSTUDENT_RT IN C1 LOOP
        UPDATE STUDENT SET RANK = VSTUDENT_RT.RANK WHERE NO =  VSTUDENT_RT.NO;
    END LOOP;
    COMMIT;
END;
/

EXECUTE STUDENT_RANK_PROC;
