-- 기존 테이블 삭제
DROP TABLE EMP01 PURGE;

-- 테이블 생성
CREATE TABLE EMP01 (
    EMPNO NUMBER(4),
    ENAME VARCHAR(10) NOT NULL,
    JOB VARCHAR(9),
    MGR NUMBER(4),
    HIREDATE DATE NOT NULL,
    SAL NUMBER(7,2) NOT NULL,
    COMM NUMBER(7,2) DEFAULT 0.0,
    DEPTNO NUMBER(2) NOT NULL
);

ALTER TABLE EMP01 ADD CONSTRAINT EMP01_EMPNO_PK PRIMARY KEY(EMPNO);

-- VALUE 값 대입
INSERT INTO EMP01 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7369, 'SMITH', 'CLEAK', 7836, TO_DATE('80/12/17', 'YY/MM/DD'), 800,0.0, 20);
INSERT INTO EMP01 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7499, 'ALLEN', 'SALESMAN', 7369, TO_DATE('87/12/20', 'YY/MM/DD'), 1600, 300, 30);
INSERT INTO EMP01 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7839, 'KING', 'PRESIDENT', NULL, TO_DATE('81/02/08', 'YY/MM/DD'), 5000,0.0, 10);

SELECT * FROM EMP01;

-- 기존 테이블 삭제
DROP TABLE MEMBERS PURGE;

-- MEMBERS 테이블 생성
CREATE TABLE MEMBERS (
    ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    REGNO VARCHAR2(14) NOT NULL,
    HP VARCHAR2(14) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL
    );

-- 임의의 VALUE 값 대입
INSERT INTO MEMBERS (ID, NAME, REGNO, HP, ADDRESS) VALUES('ABC', 'SMITH', '123456-1234567', '010-1234-5678', '경기도 광주시');
INSERT INTO MEMBERS (ID, NAME, REGNO, HP, ADDRESS) VALUES('DEF', 'ALLEN', '654321-7654321', '010-4321-8765', '서울시 강남구');

SELECT * FROM MEMBERS;

-- BOOKS 테이블 생성
CREATE TABLE BOOKS (
    CODE NUMBER(4) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    COUNT NUMBER(6) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    PUBLISH VARCHAR2(50) NOT NULL
    );

SELECT * FROM BOOKS;

-- 기존 테이블 삭제
DROP TABLE v_gogek PURGE;

-- V_GOGEK 테이블 생성
CREATE TABLE v_gogek(
    g_code NUMBER(6),
    g_name VARCHAR2(20),
    g_age NUMBER(3),
    g_tel VARCHAR2(20),
    g_addr VARCHAR2(50)
);
ALTER TABLE v_gogek ADD CONSTRAINT v_gogek_g_code_PK PRIMARY KEY(g_code);

select * from v_gogek;

-- 기존 테이블 삭제
DROP TABLE VIDEO PURGE;

-- VIDEO 테이블 생성
CREATE TABLE VIDEO(
    V_CODE NUMBER(5),
    V_TITLE VARCHAR2(50),
    V_GENRE VARCHAR2(30),
    V_PAY NUMBER(7),
    V_LEND_STATE NUMBER(1),
    V_MAKE_COMPANY VARCHAR2(50),
    V_MAKE_DATE DATE,
    V_VIEW_AGE NUMBER(1)
);
ALTER TABLE VIDEO ADD CONSTRAINT VIDEO_V_CODE_PK PRIMARY KEY(V_CODE);    
    
SELECT * FROM VIDEO;

-- 기존 테이블 삭제
DROP TABLE LEND_RETURN PURGE;

-- LEND_RETURN 테이블 생성
CREATE TABLE LEND_RETURN(
    LR_CODE NUMBER(5),
    G_CODE NUMBER(6),
    L_CODE NUMBER(5),
    L_DATE DATE,
    R_PLAN_DATE DATE,
    L_TOTAL_PAY NUMBER(7)
);
ALTER TABLE LEND_RETURN ADD CONSTRAINT v_gogek_g_code_PK FOREIGN KEY(g_code) REFERENCES v_gogek(g_code);
ALTER TABLE LEND_RETURN ADD CONSTRAINT VIDEO_v_code_PK FOREIGN KEY(V_CODE) REFERENCES VIDEO(V_CODE);

SELECT * FROM LEND_RETURN;
    