DROP TABLE SUBJECT PURGE;

-- 학과테이블
CREATE TABLE SUBJECT (
    NO NUMBER(8),
    SNUM VARCHAR2(20) NOT NULL UNIQUE,
    SNAME VARCHAR2(20) NOT NULL
);
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_NO_PK PRIMARY KEY(NO);

INSERT INTO SUBJECT (SNUM, SNAME) VALUES ('01', '컴퓨터학과');
INSERT INTO SUBJECT (SNUM, SNAME) VALUES ('02', '교육학과');
INSERT INTO SUBJECT (SNUM, SNAME) VALUES ('03', '신문방송학과');
INSERT INTO SUBJECT (SNUM, SNAME) VALUES ('04', '인터넷비즈니스과');
INSERT INTO SUBJECT (SNUM, SNAME) VALUES ('05', '기술경영과');

SELECT * FROM SUBJECT;
------------------------------------------------------------------------------
DROP TABLE STUDENT PURGE;

-- 학생테이블
CREATE TABLE STUDENT (
    NO NUMBER(8),
    NUM VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    SNUM VARCHAR2(20) NOT NULL,
    JUMIN VARCHAR2(14) NOT NULL,
    PHONE VARCHAR2(14) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    SDDATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_NO_PK PRIMARY KEY(NO);
ALTER TABLE STUDENT ADD CONSTRAINT SUBJECT_SNUM_FK FOREIGN KEY(SNUM) REFERENCES SUBJECT(SNUM);

INSERT INTO STUDENT (NO, NUM, NAME, ID, PWD, SNUM, JUMIN, PHONE, ADDRESS, EMAIL, SDDATE) VALUES(001, '06', '김정수', 'javajsp', '12345678', '01', '123456-1234567', '010-1234-5678', '서울시 서대문구 창전동', 'javajsp@naver.com', TO_DATE('06/03/01', 'YY/MM/DD'));

SELECT * FROM STUDENT;